### ISSUE TITLE
Takes 10 seconds to render a 100x100 pixel image

### ISSUE THREAD

**Issue by Meerkov** [rafael-fuente/Python-Raytracer#20]
The project says "fast" but this is not fast at all.

**Comment by rafael-fuente** [comment]
Hi Meerkov, you are right, this is not fast compared with a native GPU implementation. However, it is still much faster than a pure Python implementation, which will take several minutes to render the same image.

The good readability and simplicity of the code will help a lot of people who want to learn the basics of raytracing

**Comment by Meerkov** [comment]
switching numpy to cupy keeps the code almost identical, but still provides faster rendering

**Comment by rafael-fuente** [comment]
> switching numpy to cupy keeps the code almost identical, but still provides faster rendering

It's been quite a while since I left this project. Integrating JAX or cupy is one of the things that someone interested could do
